export const actionTypes = {
  REQUEST_ADD_TODO: 'HABIT/TODOS/REQUEST_ADD_TODO',
  REQUEST_REMOVE_TODO: 'HABIT/TODOS/REQUEST_REMOVE_TODO',
  REQUEST_TOGGLE_TODO: 'HABIT/TODOS/REQUEST_TOGGLE_TODO',
  REQUEST_GET_TODOS: 'HABIT/TODOS/REQUEST_GET_TODOS',
  REQUEST_FAILED: 'HABIT/TODOS/REQUEST_FAILED',
  ADD_TODO_SUCCESS: 'HABIT/TODOS/ADD_TODO_SUCCESS',
  GET_TODOS_SUCCESS: 'HABIT/TODOS/GET_TODOS_SUCCESS',
  REMOVE_TODO_SUCCESS: 'HABIT/TODOS/REMOVE_TODO_SUCCESS',
  TOGGLE_TODO_SUCCESS: 'HABIT/TODOS/TOGGLE_TODO_SUCCESS'
};

export default {
  addTodo: todo => ({ type: actionTypes.REQUEST_ADD_TODO, todo }),
  toggleTodo: (_id: number) => ({ type: actionTypes.REQUEST_TOGGLE_TODO, _id }),
  removeTodo: (_id: number) => ({ type: actionTypes.REQUEST_REMOVE_TODO, _id }),
  getTodos: () => ({ type: actionTypes.REQUEST_GET_TODOS })
};
